sudo: required
services:
  - docker

before_install:
  - docker build -t nicodemusmaurits/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nicodemusmaurits/docker-react npm run test
