sudo: required
services:
  - docker

before_install:
  - docker build -t nicodemusmaurits/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nicodemusmaurits/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-675529877763"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
