sudo: required
services:
  - docker

before_install:
  - docker build -t nicodemusmaurits/docker-react -f Dockerfile.dev .

script:
  - docker run nicodemusmaurits/docker-react npm run test -- --coverage
